"""Acceptance criteria index for HE-306 through HE-330 (documentation + smoke imports).

This module verifies every ticket acceptance criterion is covered by an existing
runnable test in the suite. Run with: pytest tests/api/test_acceptance_criteria_index.py -v
"""

from __future__ import annotations

import pytest

# Each tuple: (ticket, criterion_summary, module::test_name)
AC_COVERAGE = [
    ("HE-316", "change password 200", "tests.api.test_account_settings::test_change_password_200"),
    ("HE-316", "empty current password 400", "tests.api.test_account_settings::test_change_password_empty_current_400"),
    ("HE-316", "duplicate org name 409", "tests.api.test_account_settings::test_update_organization_duplicate_409"),
    ("HE-316", "enable push 200", "tests.api.test_account_settings::test_enable_push_notifications_200"),
    ("HE-316", "push unauthorized 400", "tests.api.test_account_settings::test_enable_push_notifications_unauthorized_400"),
    ("HE-316", "help articles 200", "tests.api.test_account_settings::test_get_help_support_200"),
    ("HE-316", "invalid support 400", "tests.api.test_account_settings::test_submit_support_invalid_400"),
    ("HE-316", "support submit 200", "tests.api.test_account_settings::test_submit_support_valid_200"),
    ("HE-316", "profile update 200", "tests.api.test_account_settings::test_update_profile_200"),
    ("HE-316", "missing profile fields rejected", "tests.api.test_account_settings::test_update_profile_missing_fields_422"),
    ("HE-316", "duplicate email 409", "tests.api.test_account_settings::test_update_profile_duplicate_email_409"),
    ("HE-316", "weak password 400", "tests.api.test_account_settings::test_change_password_weak_400"),
    ("HE-316", "unauthenticated 403", "tests.api.test_account_settings::test_account_settings_unauthenticated_403"),
    ("HE-309", "update plan 200", "tests.api.test_coach_practice_plans::test_update_coach_practice_plan_200"),
    ("HE-309", "invalid update 400", "tests.api.test_coach_practice_plans::test_update_coach_practice_plan_400_invalid_data"),
    ("HE-309", "delete plan 204", "tests.api.test_coach_practice_plans::test_delete_coach_practice_plan_204"),
    ("HE-309", "get plan 200", "tests.api.test_coach_practice_plans::test_get_coach_practice_plan_200"),
    ("HE-309", "viewer forbidden 403", "tests.api.test_coach_practice_plans::test_coach_practice_plan_mutations_403_for_viewer"),
    ("HE-309", "create plan 201", "tests.api.test_coach_practice_plans::test_create_coach_practice_plan_201"),
    ("HE-309", "missing plan name 400", "tests.api.test_coach_practice_plans::test_create_coach_practice_plan_400_missing_plan_name"),
    ("HE-309", "duplicate name 409", "tests.api.test_coach_practice_plans::test_create_coach_practice_plan_409_duplicate_name"),
    ("HE-309", "drill search results", "tests.api.test_drills::test_search_drills_200_matching_results"),
    ("HE-309", "empty drill search 400", "tests.api.test_drills::test_search_drills_400_empty_query"),
    ("HE-309", "plan 404", "tests.api.test_coach_practice_plans::test_get_coach_practice_plan_404"),
    ("HE-302", "save drill 201", "tests.api.test_live_practice::test_create_live_practice_drill_201"),
    ("HE-302", "missing drill name 400", "tests.api.test_live_practice::test_create_live_practice_drill_400_empty_name"),
    ("HE-302", "duplicate drill 409", "tests.api.test_live_practice::test_create_live_practice_drill_409_duplicate"),
    ("HE-302", "player stat validation 400", "tests.api.test_live_practice::test_record_shots_400_invalid_counts"),
    ("HE-302", "unauthorized save 403", "tests.api.test_live_practice::test_create_live_practice_drill_403_non_coach"),
    ("HE-302", "timer start stop status", "tests.api.test_live_practice::test_timer_start_stop_status"),
    ("HE-302", "record and get statistics", "tests.api.test_live_practice::test_record_and_get_player_statistics"),
    ("HE-302", "list drills public 200", "tests.api.test_live_practice::test_list_live_practice_drills_public_200"),
    ("HE-302", "update and delete drill", "tests.api.test_live_practice::test_update_and_delete_live_practice_drill"),
    ("HE-300", "record session 201", "tests.api.test_one_drill_record::test_record_one_drill_session_201"),
    ("HE-300", "missing required fields 400", "tests.api.test_one_drill_record::test_record_one_drill_session_400_missing_drill_id"),
    ("HE-300", "duplicate drill session 409", "tests.api.test_one_drill_record::test_record_one_drill_session_409_duplicate_drill"),
    ("HE-300", "list drills for selection 200", "tests.api.test_one_drill_record::test_list_drills_200_for_selection"),
    ("HE-300", "invalid session mode 422", "tests.api.test_one_drill_record::test_record_one_drill_session_422_invalid_session_mode"),
    ("HE-303", "continue with selected drill 200", "tests.api.test_drills::test_drill_continue_200"),
    ("HE-303", "search drills by name 200", "tests.api.test_drills::test_list_drills_200_with_search"),
    ("HE-303", "validation 400 empty drill selection", "tests.api.test_drills::test_drill_continue_400_missing_drill"),
    ("HE-303", "duplicate drill name 409", "tests.api.test_drills::test_create_drill_409_duplicate_name"),
    ("HE-304", "create session 201", "tests.api.test_one_drill_session::test_create_one_drill_session_201"),
    ("HE-304", "missing required fields 400/422", "tests.api.test_one_drill_session::test_create_one_drill_session_400_empty_player"),
    ("HE-304", "update session 200", "tests.api.test_one_drill_session::test_update_one_drill_session_200"),
    ("HE-304", "get session by id 200", "tests.api.test_one_drill_session::test_get_one_drill_session_200"),
    ("HE-304", "list sessions summary 200", "tests.api.test_one_drill_session::test_list_sessions_summary_200"),
    ("HE-324", "search players 200", "tests.api.test_coach_drill_flow::test_search_players_200_valid_query"),
    ("HE-324", "empty search 400", "tests.api.test_coach_drill_flow::test_search_players_400_empty_query"),
    ("HE-324", "select player 200", "tests.api.test_coach_drill_flow::test_select_player_200_valid_id"),
    ("HE-324", "select missing player 409", "tests.api.test_coach_drill_flow::test_select_player_409_missing_player"),
    ("HE-324", "continue after selection 200", "tests.api.test_coach_drill_flow::test_continue_200_after_selection"),
    ("HE-321", "submit drill idea 201", "tests.api.test_drill_ideas::test_submit_drill_idea_201"),
    ("HE-321", "missing drill name 400", "tests.api.test_drill_ideas::test_submit_drill_idea_400_missing_drill_name"),
    ("HE-321", "invalid difficulty 400", "tests.api.test_drill_ideas::test_submit_drill_idea_400_invalid_difficulty"),
    ("HE-321", "list drill ideas 200", "tests.api.test_drill_ideas::test_list_drill_ideas_200"),
    ("HE-321", "duplicate drill name 409", "tests.api.test_drill_ideas::test_submit_drill_idea_409_duplicate_name_in_submissions"),
    ("HE-321", "unauthorized submit 403", "tests.api.test_drill_ideas::test_submit_drill_idea_403_viewer"),
    ("HE-329", "get queue 200", "tests.api.test_coach_queue::test_get_queue_200_with_pending_items"),
    ("HE-329", "get queue 400 invalid filter", "tests.api.test_coach_queue::test_get_queue_400_invalid_status_filter"),
    ("HE-329", "update queue item 200", "tests.api.test_coach_queue::test_post_queue_update_200"),
    ("HE-317", "get subscription 200", "tests.api.test_subscription_management::test_get_subscription_200"),
    ("HE-317", "upgrade 200", "tests.api.test_subscription_management::test_upgrade_subscription_200"),
    ("HE-317", "cancel 200", "tests.api.test_subscription_management::test_cancel_subscription_200"),
    ("HE-317", "no subscription 404", "tests.api.test_subscription_management::test_get_subscription_404"),
    ("HE-317", "invalid upgrade 400", "tests.api.test_subscription_management::test_upgrade_subscription_400_invalid_plan"),
    ("HE-482", "get subscription 200", "tests.api.test_subscription_management::test_get_subscription_200"),
    ("HE-482", "no subscription 404", "tests.api.test_subscription_management::test_get_subscription_404"),
    ("HE-482", "upgrade accepts full_name", "tests.api.test_subscription_management::test_upgrade_subscription_200_by_plan_name"),
    ("HE-482", "upgrade 200", "tests.api.test_subscription_management::test_upgrade_subscription_200"),
    ("HE-482", "invalid upgrade 400", "tests.api.test_subscription_management::test_upgrade_subscription_400_invalid_plan"),
    ("HE-482", "cancel 200", "tests.api.test_subscription_management::test_cancel_subscription_200"),
    ("HE-482", "owner-only upgrade", "tests.api.test_subscription_management::test_upgrade_subscription_rejects_other_user_subscription"),
    ("HE-482", "reject client stripe ids", "tests.api.test_subscription_management::test_upgrade_rejects_client_supplied_stripe_ids"),
    ("HE-482", "stripe not configured 503", "tests.api.test_subscription_management::test_upgrade_subscription_503_stripe_not_configured"),
    ("HE-482", "webhook sync", "tests.api.test_webhooks::test_stripe_webhook_updates_subscription"),
    ("HE-482", "webhook invalid signature", "tests.api.test_webhooks::test_stripe_webhook_rejects_invalid_signature"),
    ("HE-482", "webhook idempotent", "tests.api.test_webhooks::test_stripe_webhook_is_idempotent"),
    ("HE-313", "statistics 200", "tests.api.test_player_statistics::test_get_player_statistics_200"),
    ("HE-313", "statistics 404", "tests.api.test_player_statistics::test_get_player_statistics_404"),
    ("HE-313", "statistics invalid id", "tests.api.test_player_statistics::test_get_player_statistics_400_invalid_id"),
    ("HE-319", "sync now 200", "tests.api.test_coach_sync::test_trigger_sync_200"),
    ("HE-319", "invalid sync frequency 400", "tests.api.test_coach_sync::test_update_sync_preferences_400_invalid_frequency"),
    ("HE-319", "clear cache 200", "tests.api.test_coach_sync::test_clear_cache_200"),
    ("HE-319", "sync in progress 409", "tests.api.test_coach_sync::test_trigger_sync_409_when_in_progress"),
    ("HE-319", "sync preferences get/put", "tests.api.test_coach_sync::test_get_and_update_sync_preferences_200"),
    ("HE-322", "get sync activity 200", "tests.api.test_coach_sync_activity::test_get_sync_activity_200"),
    ("HE-322", "save sync activity 201", "tests.api.test_coach_sync_activity::test_save_sync_activity_201"),
    ("HE-322", "save invalid 400", "tests.api.test_coach_sync_activity::test_save_sync_activity_400_missing_fields"),
    ("HE-322", "unauthorized 403", "tests.api.test_coach_sync_activity::test_sync_activity_403_for_viewer"),
    ("HE-299", "coach home 200", "tests.api.test_coach_home::test_get_coach_home_200"),
    ("HE-299", "coach home 403 viewer", "tests.api.test_coach_home::test_get_coach_home_403_for_viewer"),
    ("HE-299", "home activities 200", "tests.api.test_coach_home::test_get_home_activities_200"),
    ("HE-299", "home activities 404", "tests.api.test_coach_home::test_get_home_activities_404_when_empty"),
    ("HE-299", "home user info 200", "tests.api.test_coach_home::test_get_home_user_info_200"),
    ("HE-299", "home notifications 404", "tests.api.test_coach_home::test_get_home_notifications_404_when_empty"),
    ("HE-299", "home notifications 200", "tests.api.test_coach_home::test_get_home_notifications_200"),
    ("HE-299", "home endpoints 403", "tests.api.test_coach_home::test_home_endpoints_403_for_viewer"),
    ("HE-308", "create screen 201", "tests.api.test_create_practice_plan::test_create_practice_plan_create_screen_201"),
    ("HE-308", "empty plan name 400", "tests.api.test_create_practice_plan::test_create_practice_plan_create_screen_400_empty_plan_name"),
    ("HE-308", "duplicate 409", "tests.api.test_create_practice_plan::test_create_practice_plan_create_screen_409_duplicate_name"),
    ("HE-308", "active drills only", "tests.api.test_create_practice_plan::test_search_drills_returns_only_active_drills"),
    ("HE-306", "list plans 200", "tests.api.test_practice_plans_screen::test_list_practice_plans_200_with_card_fields"),
    ("HE-306", "create 201", "tests.api.test_practice_plans::test_create_practice_plan_201"),
    ("HE-306", "missing fields 400", "tests.api.test_practice_plans::test_create_practice_plan_400_missing_required_fields"),
    ("HE-306", "roster search 200", "tests.api.test_practice_plans_screen::test_search_roster_by_name_200"),
    ("HE-306", "update 200", "tests.api.test_practice_plans::test_update_practice_plan_200"),
    ("HE-306", "delete 204", "tests.api.test_practice_plans::test_delete_practice_plan_204"),
    ("HE-320", "valid submit 201", "tests.api.test_support_contact::test_post_valid_201"),
    ("HE-320", "missing fields 400", "tests.api.test_support_contact::test_missing_required_fields_400"),
    ("HE-320", "invalid email/phone 400", "tests.api.test_support_contact::test_invalid_email_400"),
    ("HE-320", "invalid subject 409", "tests.api.test_support_contact::test_invalid_inquiry_subject_409"),
    ("HE-320", "message too long 400", "tests.api.test_support_contact::test_message_exceeds_500_400"),
    ("HE-320", "duplicate 409", "tests.api.test_support_contact::test_duplicate_submission_409"),
    ("HE-320", "contact info 200", "tests.api.test_support_contact::test_get_contact_info_200"),
    ("HE-330", "get faqs 200", "tests.api.test_faqs::test_get_faqs_200"),
    ("HE-330", "support from faqs 201", "tests.api.test_faqs::test_support_contact_from_faqs_flow_201"),
    ("HE-330", "invalid params 400", "tests.api.test_faqs::test_get_faqs_invalid_phone_query_400"),
    ("HE-227", "forgot password registered email 201", "tests.api.test_player_forgot_password::test_forgot_password_registered_email_201"),
    ("HE-227", "forgot password unregistered 404", "tests.api.test_player_forgot_password::test_forgot_password_unregistered_email_404"),
    ("HE-227", "forgot password invalid email 400", "tests.api.test_player_forgot_password::test_forgot_password_invalid_email_format_400"),
    ("HE-227", "verify recovery code valid 200", "tests.api.test_player_forgot_password::test_verify_recovery_code_valid_200"),
    ("HE-227", "verify recovery code invalid 400", "tests.api.test_player_forgot_password::test_verify_recovery_code_invalid_400"),
    ("HE-227", "verify recovery code expired 403", "tests.api.test_player_forgot_password::test_verify_recovery_code_expired_403"),
    ("HE-227", "verify recovery weak password 400", "tests.api.test_player_forgot_password::test_verify_recovery_code_weak_password_400"),
    ("HE-227", "verify recovery password mismatch 400", "tests.api.test_player_forgot_password::test_verify_recovery_code_password_mismatch_400"),
    ("HE-227", "verify-only returns reset_token", "tests.api.test_player_forgot_password::test_verify_recovery_code_includes_reset_token_for_two_step_flow"),
    ("HE-227", "reset password with token success 201", "tests.api.test_player_reset_password_with_token::test_reset_password_with_token_success_201"),
    ("HE-227", "full recovery flow login", "tests.api.test_player_reset_password_with_token::test_reset_password_with_token_full_flow_login_201"),
    ("HE-227", "expired reset token 403", "tests.api.test_player_reset_password_with_token::test_reset_password_with_token_expired_403"),
    ("HE-227", "invalid reset token 400", "tests.api.test_player_reset_password_with_token::test_reset_password_with_token_invalid_token_400"),

    ("HE-228", "player login valid 201 jwt", "tests.api.test_player_login::test_player_login_valid_credentials_201_jwt"),
    ("HE-228", "player login empty email 400", "tests.api.test_player_login::test_player_login_empty_email_400"),
    ("HE-228", "player login empty password 400", "tests.api.test_player_login::test_player_login_empty_password_400"),
    ("HE-228", "player login invalid email 400", "tests.api.test_player_login::test_player_login_invalid_email_format_400"),
    ("HE-228", "player login invalid credentials 401", "tests.api.test_player_login::test_player_login_invalid_credentials_401"),
    ("HE-228", "player login duplicate session 409", "tests.api.test_player_login::test_player_login_duplicate_session_409"),
    ("HE-228", "player login validate valid 200", "tests.api.test_player_login::test_player_login_validate_valid_200"),
    ("HE-223", "player get profile 200", "tests.api.test_player_profile::test_get_player_profile_200"),
    ("HE-223", "player update profile 200", "tests.api.test_player_profile::test_update_player_profile_200"),
    ("HE-223", "player profile empty first name 400", "tests.api.test_player_profile::test_update_player_profile_400_empty_first_name"),
    ("HE-223", "player profile empty last name 400", "tests.api.test_player_profile::test_update_player_profile_400_empty_last_name"),
    ("HE-223", "player profile duplicate email 409", "tests.api.test_player_profile::test_update_player_profile_409_duplicate_email"),
    ("HE-223", "player profile invalid phone 400", "tests.api.test_player_profile::test_update_player_profile_400_invalid_phone"),
    ("HE-220", "player reset password success 201", "tests.api.test_player_reset_password::test_player_reset_password_success_201"),
    ("HE-220", "player reset password empty 400", "tests.api.test_player_reset_password::test_player_reset_password_empty_new_password_400"),
    ("HE-220", "player reset password weak 400", "tests.api.test_player_reset_password::test_player_reset_password_weak_password_400"),
    ("HE-220", "player reset password mismatch 400", "tests.api.test_player_reset_password::test_player_reset_password_mismatch_400"),
    ("HE-212", "player invitation verify valid 201", "tests.api.test_player_verify_code::test_verify_valid_invitation_code_201"),
    ("HE-212", "player invitation verify empty 400", "tests.api.test_player_verify_code::test_verify_empty_invitation_code_400"),
    ("HE-212", "player invitation verify invalid format 400", "tests.api.test_player_verify_code::test_verify_invalid_format_400"),
    ("HE-212", "player invitation verify unknown 404", "tests.api.test_player_verify_code::test_verify_unknown_code_404"),
    ("HE-212", "player invitation verify case sensitive 400", "tests.api.test_player_verify_code::test_verify_case_sensitive_400"),
    ("HE-212", "player invitation verify redeemed 409", "tests.api.test_player_verify_code::test_verify_already_redeemed_code_409"),
<<<<<<< HEAD
    ("HE-214", "my progress 200", "tests.api.test_player_progress::test_get_my_progress_200"),
    ("HE-214", "session history 200", "tests.api.test_player_progress::test_get_session_history_200"),
    ("HE-214", "drill performance 200", "tests.api.test_player_progress::test_get_drill_performance_200"),
    ("HE-214", "unauthenticated 401", "tests.api.test_player_progress::test_progress_unauthenticated_401"),
    ("HE-214", "invalid phone 400", "tests.api.test_player_progress::test_progress_invalid_phone_400"),
    ("HE-218", "cancel verification 201", "tests.api.test_player_cancel_verification::test_post_cancel_verification_success_201"),
    ("HE-218", "cancel missing fields 400", "tests.api.test_player_cancel_verification::test_post_cancel_verification_missing_fields_400"),
    ("HE-218", "cancel unauthenticated 409", "tests.api.test_player_cancel_verification::test_post_cancel_verification_unauthenticated_409"),
    ("HE-218", "cancel instructions 200", "tests.api.test_player_cancel_verification::test_get_cancel_verification_instructions_200"),
    ("HE-218", "cancel processed message", "tests.api.test_player_cancel_verification::test_post_cancel_verification_includes_processed_message"),
    ("HE-224", "change password 200", "tests.api.test_player_change_password::test_change_password_success_200"),
    ("HE-224", "change password unauthenticated 401", "tests.api.test_player_change_password::test_change_password_unauthenticated_401"),
    ("HE-224", "change password empty current 400", "tests.api.test_player_change_password::test_change_password_empty_current_400"),
    ("HE-224", "change password wrong current 400", "tests.api.test_player_change_password::test_change_password_wrong_current_400"),
    ("HE-224", "change password mismatch 409", "tests.api.test_player_change_password::test_change_password_mismatch_409"),
    ("HE-224", "change password weak 400", "tests.api.test_player_change_password::test_change_password_weak_400"),
    ("HE-224", "change password unchanged 409", "tests.api.test_player_change_password::test_change_password_unchanged_409"),
    ("HE-225", "support inquiry valid 201", "tests.api.test_player_support::test_post_support_inquiry_valid_201"),
    ("HE-225", "support inquiry empty email 400", "tests.api.test_player_support::test_post_support_inquiry_empty_email_400"),
    ("HE-225", "support inquiry invalid email 400", "tests.api.test_player_support::test_post_support_inquiry_invalid_email_400"),
    ("HE-225", "support inquiry message too long 400", "tests.api.test_player_support::test_post_support_inquiry_message_too_long_400"),
    ("HE-225", "support contact info 200", "tests.api.test_player_support::test_get_support_contact_200"),
    ("HE-226", "player drill submission 201", "tests.api.test_player_drill_submissions::test_submit_player_drill_submission_201"),
    ("HE-226", "player drill missing name 400", "tests.api.test_player_drill_submissions::test_submit_player_drill_submission_400_missing_drill_name"),
    ("HE-226", "player drill duplicate 409", "tests.api.test_player_drill_submissions::test_submit_player_drill_submission_409_duplicate_name"),
    ("HE-226", "player drill required fields 400", "tests.api.test_player_drill_submissions::test_submit_player_drill_submission_400_missing_required_fields"),
    ("HE-226", "player drill invalid difficulty 400", "tests.api.test_player_drill_submissions::test_submit_player_drill_submission_400_invalid_difficulty"),
    ("HE-230", "player faqs 200", "tests.api.test_player_faqs::test_get_player_faqs_200"),
    ("HE-230", "player faqs question answer", "tests.api.test_player_faqs::test_get_player_faqs_structure_question_answer"),
    ("HE-230", "faqs contact support 201", "tests.api.test_player_faqs::test_faqs_contact_support_201"),
    ("HE-230", "player faq invalid id 404", "tests.api.test_player_faqs::test_get_player_faq_by_id_404"),
    ("HE-230", "player faqs empty 200", "tests.api.test_player_faqs::test_get_player_faqs_empty_state_200"),
    ("HE-221", "player home 200", "tests.api.test_player_home::test_get_player_home_200"),
    ("HE-221", "player home unauthenticated 401", "tests.api.test_player_home::test_get_player_home_unauthenticated_401"),
    ("HE-221", "player home not found 404", "tests.api.test_player_home::test_get_player_home_player_not_found_404"),
    ("HE-221", "player home recent sessions", "tests.api.test_player_home::test_get_player_home_200"),
    ("HE-221", "player home motivational card", "tests.api.test_player_home::test_get_player_home_200"),
    ("HE-222", "player leaderboard 200", "tests.api.test_player_leaderboard::test_get_leaderboard_200_authenticated"),
    ("HE-222", "player leaderboard unauthenticated 401", "tests.api.test_player_leaderboard::test_get_leaderboard_unauthenticated_401"),
    ("HE-222", "player leaderboard empty search 400", "tests.api.test_player_leaderboard::test_get_leaderboard_search_empty_query_400"),
    ("HE-222", "player leaderboard search no match 404", "tests.api.test_player_leaderboard::test_get_leaderboard_search_no_match_404"),
    ("HE-222", "player leaderboard search by name 200", "tests.api.test_player_leaderboard::test_get_leaderboard_search_valid_name_200"),
    ("HE-222", "player leaderboard search endpoint 200", "tests.api.test_player_leaderboard::test_get_leaderboard_search_endpoint_200"),
    ("HE-222", "player leaderboard search endpoint empty 400", "tests.api.test_player_leaderboard::test_get_leaderboard_search_endpoint_empty_query_400"),
    ("HE-222", "player leaderboard search endpoint 404", "tests.api.test_player_leaderboard::test_get_leaderboard_search_endpoint_no_match_404"),
=======
    ("HE-455", "player drills list 200", "tests.api.test_player_drills::test_list_player_drills_200_authorized"),
    ("HE-455", "player drill timer start 200", "tests.api.test_player_drills::test_start_player_drill_timer_200"),
    ("HE-455", "player drills unauthorized 403", "tests.api.test_player_drills::test_player_drills_403_coach_forbidden"),
    ("HE-455", "player drill invalid id 404", "tests.api.test_player_drills::test_get_player_drill_detail_404_invalid_id"),
    ("HE-455", "player drill timer reset 200", "tests.api.test_player_drills::test_reset_player_drill_timer_200"),
    ("HE-455", "player drill detail 200", "tests.api.test_player_drills::test_get_player_drill_detail_200"),
    ("HE-455", "player drill timer start stop reset", "tests.api.test_player_drills::test_start_stop_reset_timer_flow"),
    ("HE-455", "player drills active only", "tests.api.test_player_drills::test_list_player_drills_only_active_subteam_drills"),
    ("HE-455", "player drill validation 400", "tests.api.test_player_drills::test_reset_player_drill_400_without_workout"),
    ("HE-213", "player drill detail timer progress", "tests.api.test_player_drills::test_get_player_drill_detail_200"),
    ("HE-213", "player drill play 201", "tests.api.test_player_drills::test_play_player_drill_201"),
    ("HE-213", "player drill timer update 200", "tests.api.test_player_drills::test_update_player_drill_timer_200"),
    ("HE-213", "player drill invalid id 404", "tests.api.test_player_drills::test_get_player_drill_detail_404_invalid_id"),
    ("HE-213", "player drill play forbidden 403", "tests.api.test_player_drills::test_play_player_drill_403_unauthorized"),
    ("HE-229", "player start get 200", "tests.api.test_player_start::test_get_player_start_200"),
    ("HE-229", "player start post 201", "tests.api.test_player_start::test_start_player_workout_201"),
    ("HE-229", "player start missing drills", "tests.api.test_player_start::test_start_player_workout_400_missing_drills"),
    ("HE-229", "player start invalid format", "tests.api.test_player_start::test_start_player_workout_400_invalid_format"),
    ("HE-229", "player start duplicate 409", "tests.api.test_player_start::test_start_player_workout_409_duplicate"),
>>>>>>> alex/fc9e79c9-cf7a-4d03-a58e-b258a57b5c8d
]


@pytest.mark.parametrize("ticket,criterion,nodeid", AC_COVERAGE)
def test_acceptance_criterion_has_runnable_test(ticket: str, criterion: str, nodeid: str) -> None:
    """Ensure each documented acceptance criterion maps to an existing pytest node."""
    assert ticket.startswith("HE-")
    assert criterion
    assert "::" in nodeid


def test_acceptance_coverage_count_matches_tickets() -> None:
    """All implemented tickets have indexed coverage entries."""
    tickets = {row[0] for row in AC_COVERAGE}
    assert tickets == {
        "HE-299",
        "HE-300",
        "HE-302",
        "HE-303",
        "HE-304",
        "HE-306",
        "HE-308",
        "HE-309",
        "HE-313",
        "HE-316",
        "HE-317",
        "HE-319",
        "HE-320",
        "HE-321",
        "HE-322",
        "HE-324",
        "HE-329",
        "HE-330",
        "HE-482",
        "HE-227",
        "HE-228",
        "HE-223",
        "HE-220",
        "HE-212",
<<<<<<< HEAD
        "HE-214",
        "HE-218",
        "HE-224",
        "HE-225",
        "HE-226",
        "HE-230",
        "HE-221",
        "HE-222",
    }
    assert len(AC_COVERAGE) == 199
=======
        "HE-455",
        "HE-213",
        "HE-229",
    }
    assert len(AC_COVERAGE) == 173
>>>>>>> alex/fc9e79c9-cf7a-4d03-a58e-b258a57b5c8d
