"""alex auto

Revision ID: 17d7851bcd17
Revises: g3b4c5d6e7f8
Create Date: 2026-08-27 14:11:57.256251

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '17d7851bcd17'
down_revision: str | Sequence[str] | None = 'g3b4c5d6e7f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
