"""alex auto

Revision ID: 1d00751fba09
Revises: o8p9q0r1s2t3
Create Date: 2026-08-31 16:10:44.117883

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1d00751fba09'
down_revision: str | Sequence[str] | None = 'o8p9q0r1s2t3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
