"""alex auto

Revision ID: 312e76ed6d4e
Revises: l5e6f7g8h9i0
Create Date: 2026-08-31 15:14:40.539699

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '312e76ed6d4e'
down_revision: str | Sequence[str] | None = 'l5e6f7g8h9i0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
