"""alex auto

Revision ID: 5a0d230693b5
Revises: d4e8f1a2b3c5
Create Date: 2026-08-27 13:37:29.048731

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5a0d230693b5'
down_revision: str | Sequence[str] | None = 'd4e8f1a2b3c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
