"""alex auto

Revision ID: 5bedb014c8fd
Revises: 91e34c6862bc
Create Date: 2026-08-31 11:36:58.350245

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5bedb014c8fd'
down_revision: str | Sequence[str] | None = '91e34c6862bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
