"""alex auto

Revision ID: 606d3ccbebdb
Revises: cd6841715b00
Create Date: 2026-08-27 16:04:22.834179

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '606d3ccbebdb'
down_revision: str | Sequence[str] | None = 'cd6841715b00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
