"""alex auto

Revision ID: 6891c775f9fd
Revises: 5bedb014c8fd
Create Date: 2026-08-31 13:04:27.761563

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6891c775f9fd'
down_revision: str | Sequence[str] | None = '5bedb014c8fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
