"""alex auto

Revision ID: 807d5c5056ea
Revises: 6891c775f9fd
Create Date: 2026-08-31 14:00:33.650884

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '807d5c5056ea'
down_revision: str | Sequence[str] | None = '6891c775f9fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
