"""alex auto

Revision ID: 91e34c6862bc
Revises: bc961a17106c
Create Date: 2026-08-27 17:57:24.489776

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '91e34c6862bc'
down_revision: str | Sequence[str] | None = 'bc961a17106c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
