"""alex auto

Revision ID: ad3569c0735d
Revises: 1d00751fba09
Create Date: 2026-08-31 18:17:28.531827

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ad3569c0735d'
down_revision: str | Sequence[str] | None = '1d00751fba09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
