"""alex auto

Revision ID: bc961a17106c
Revises: 606d3ccbebdb
Create Date: 2026-08-27 17:13:47.648827

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bc961a17106c'
down_revision: str | Sequence[str] | None = '606d3ccbebdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
