"""alex auto

Revision ID: bf1468d0858b
Revises: cb8267ab2bb1
Create Date: 2026-08-27 10:36:00.268201

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bf1468d0858b'
down_revision: str | Sequence[str] | None = 'cb8267ab2bb1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
