"""initial

Revision ID: cb8267ab2bb1
Revises: 
Create Date: 2026-08-26 16:52:08.214060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb8267ab2bb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sport', sa.Text(), nullable=True),
    sa.Column('gender_focus', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('admin_email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('join_code', sa.Text(), nullable=True),
    sa.Column('subscription_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('subscription_plans_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_frequency', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_amount_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('teams_limit_type', sa.String(length=16), nullable=False),
    sa.Column('teams_count', sa.Integer(), nullable=True),
    sa.Column('coaches_limit_type', sa.String(length=16), nullable=True),
    sa.Column('coaches_count', sa.Integer(), nullable=True),
    sa.Column('players_limit_type', sa.String(length=16), nullable=False),
    sa.Column('players_count', sa.Integer(), nullable=True),
    sa.Column('historical_records_duration', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_offline_sync', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replacement_plan_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_frequency IN ('monthly', 'yearly')", name='subscription_plans_staging_billing_frequency_check'),
    sa.CheckConstraint("historical_records_duration IN ('1_month', '3_months', '6_months', '1_year', 'unlimited')", name='subscription_plans_staging_historical_records_check'),
    sa.CheckConstraint("players_limit_type IN ('limited', 'unlimited')", name='subscription_plans_staging_players_limit_type_check'),
    sa.CheckConstraint("role IN ('org_admin', 'coach')", name='subscription_plans_staging_role_check'),
    sa.CheckConstraint("teams_limit_type IN ('limited', 'unlimited')", name='subscription_plans_staging_teams_limit_type_check'),
    sa.ForeignKeyConstraint(['replacement_plan_id'], ['subscription_plans_staging.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    op.create_index(op.f('ix_subscription_plans_staging_archived_at'), 'subscription_plans_staging', ['archived_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_staging_billing_frequency'), 'subscription_plans_staging', ['billing_frequency'], unique=False)
    op.create_index(op.f('ix_subscription_plans_staging_name'), 'subscription_plans_staging', ['name'], unique=False)
    op.create_index(op.f('ix_subscription_plans_staging_replacement_plan_id'), 'subscription_plans_staging', ['replacement_plan_id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_staging_role'), 'subscription_plans_staging', ['role'], unique=False)
    op.create_table('support_requests_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_stored_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=255), nullable=True),
    sa.Column('attachment_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_staging_email'), 'support_requests_staging', ['email'], unique=False)
    op.create_index(op.f('ix_support_requests_staging_subject'), 'support_requests_staging', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_token', sa.String(length=255), nullable=True),
    sa.Column('recovery_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_user_meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('super_admin', 'org_admin', 'coach', 'player')", name='users_role_check'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('revoked_tokens_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_staging_token_id'), 'revoked_tokens_staging', ['token_id'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_staging_user_id'), 'revoked_tokens_staging', ['user_id'], unique=False)
    op.create_table('stripe_subscriptions_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_user_id', sa.UUID(), nullable=True),
    sa.Column('subscriber_email', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pending_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pending_plan_id'], ['subscription_plans_staging.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans_staging.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_subscriptions_staging_pending_plan_id'), 'stripe_subscriptions_staging', ['pending_plan_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_plan_id'), 'stripe_subscriptions_staging', ['plan_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_status'), 'stripe_subscriptions_staging', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_stripe_customer_id'), 'stripe_subscriptions_staging', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_stripe_price_id'), 'stripe_subscriptions_staging', ['stripe_price_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_stripe_subscription_id'), 'stripe_subscriptions_staging', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_stripe_subscriptions_staging_subscriber_email'), 'stripe_subscriptions_staging', ['subscriber_email'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_staging_subscriber_user_id'), 'stripe_subscriptions_staging', ['subscriber_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_subscriptions_staging_subscriber_user_id'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_subscriber_email'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_stripe_subscription_id'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_stripe_price_id'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_stripe_customer_id'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_status'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_plan_id'), table_name='stripe_subscriptions_staging')
    op.drop_index(op.f('ix_stripe_subscriptions_staging_pending_plan_id'), table_name='stripe_subscriptions_staging')
    op.drop_table('stripe_subscriptions_staging')
    op.drop_index(op.f('ix_revoked_tokens_staging_user_id'), table_name='revoked_tokens_staging')
    op.drop_index(op.f('ix_revoked_tokens_staging_token_id'), table_name='revoked_tokens_staging')
    op.drop_table('revoked_tokens_staging')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_support_requests_staging_subject'), table_name='support_requests_staging')
    op.drop_index(op.f('ix_support_requests_staging_email'), table_name='support_requests_staging')
    op.drop_table('support_requests_staging')
    op.drop_index(op.f('ix_subscription_plans_staging_role'), table_name='subscription_plans_staging')
    op.drop_index(op.f('ix_subscription_plans_staging_replacement_plan_id'), table_name='subscription_plans_staging')
    op.drop_index(op.f('ix_subscription_plans_staging_name'), table_name='subscription_plans_staging')
    op.drop_index(op.f('ix_subscription_plans_staging_billing_frequency'), table_name='subscription_plans_staging')
    op.drop_index(op.f('ix_subscription_plans_staging_archived_at'), table_name='subscription_plans_staging')
    op.drop_table('subscription_plans_staging')
    op.drop_table('organizations')
    # ### end Alembic commands ###
