"""alex auto

Revision ID: cd6841715b00
Revises: h1a2b3c4d5e6
Create Date: 2026-08-27 15:03:46.730276

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'cd6841715b00'
down_revision: str | Sequence[str] | None = 'h1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
